site_name: Respect Bank
site_url: https://respectbank.groza.dev/
repo_url: https://github.com/agroza-dev/respect-bank-site

theme:
  name: material

nav:
  - Главная: index.md
  - Механики: mechanics.md
  - Документация:
      - Трансферы: docs/transfers.md
      - Реакции: docs/reactions.md
  - Обновления:
      - 0.1: release-notes/0.1.md